site_name: foozy
theme:
  name: cluster

nav:
  - General: index.md
  - Getting started: getting_started.md
  - Cmd and config:
    - Cmd: cmd_and_config/cmd.md
    - Config: cmd_and_config/config.md
  - Router:
    - Router: router/router.md
    - Websocket: router/websocket.md
    - Cookies: router/cookies/cookies.md
    - Manager: router/manager/manager.md
    - Form: router/form/form.md
    - Middlewares: router/middlewares/middlewares.md
    - Tmlengine: router/tmlengine/tmlengine.md
  - Secure:
    - CSRF token: secure/csrf_token.md
    - HMAC: secure/hmac.md
    - JWT: secure/jwt.md
    - Key: secure/key.md
    - Header: secure/header.md
  - Codegen: codegen/gen.md
  - Debug: debug/logging.md
  - Builtin: builtin/builtin.md
  - Typeopr: typeopr/typeopr.md
  - Server:
    - Server: server/server.md
    - Globalflow: server/globalflow/globalflow.md
    - Livereload: server/livereload/livereload.md